version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    environment:
      DOCKER_HOST: "unix:///var/run/docker.sock"
    volumes:
      - ./stack/script.sh:/etc/localstack/init/ready.d/script.sh
      - '/var/run/docker.sock:/var/run/docker.sock'

  update:
    build: .
    ports:
      - '9000:8080'
    environment:
      AWS_REGION: "eu-central-1"
      AWS_DEFAULT_REGION: "eu-central-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      S3_ENDPOINT: "http://localstack:4566"
      AV_DEFINITION_S3_BUCKET: "av-definitions"


  scan:
    build: .
    ports:
      - '9001:8080'
    environment:
      AWS_REGION: "eu-central-1"
      AWS_DEFAULT_REGION: "eu-central-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      S3_ENDPOINT: "http://localstack:4566"
      SNS_ENDPOINT: "http://localstack:4566"
      AV_DEFINITION_S3_BUCKET: "av-definitions"
    command: "scan.lambda_handler"
