############
#
# Caches
#
# Caches may require a prefix, since caches in CircleCI 2.0 are immutable.
# A prefix provides an easy way to invalidate a cache.  See https://circleci.com/docs/2.0/caching/#clearing-cache
#
############

version: "2.1"

executors:
  primary:
    docker:
      - image: docker:17.05.0-ce
  python_test:
    docker:
      - image: circleci/python:3.7-stretch
  pre_commit_test:
    docker:
      - image: circleci/python:3.7-stretch
  publish:
    docker:
      - image: 307238562370.dkr.ecr.eu-west-1.amazonaws.com/voltti/builder-aws:3d8dc11fab99458b51f342b4afef93a4272b0f69

jobs:
  # `build` is used for building the archive
  build:
    executor: primary
    working_directory: ~/src
    steps:
      - setup_remote_docker:
          reusable: true    # default - false
          exclusive: true   # default - true
      - run:
          name: Dependencies
          command: apk add --no-cache make git curl openssh
      - checkout
      - run:
          name: Build
          command: make archive
      - run: |
          docker create --name bucket-antivirus-function-builder bucket-antivirus-function:latest
          trap "docker rm bucket-antivirus-function-builder" EXIT
          docker cp bucket-antivirus-function-builder:/opt/app/build/lambda.zip ./build/lambda.zip
      - persist_to_workspace:
          root: ./
          paths:
            - build/

  publish:
    executor: publish
    environment:
      ARTIFACT: ./build/
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Publish to S3
          command: |
            export PROJECT="${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
            export VERSION="${CIRCLE_TAG:-latest-${CIRCLE_BRANCH}}"
            persist-artifact

  # `pre_commit_deps` is used for cache pre-commit sources
  pre_commit_deps:
    executor: pre_commit_test
    steps:
      - checkout

      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run: sudo pip install pre-commit==1.18.3
      - run: pre-commit install-hooks

      - save_cache:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit

  # `pre_commit_test` is used to run pre-commit hooks on all files
  pre_commit_test:
    executor: pre_commit_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run: sudo pip install pre-commit==1.18.3
      - run:
          name: Run pre-commit tests
          command: pre-commit run --all-files

  # `test` is used to run python tests
  test:
    executor: python_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run: sudo pip install -r requirements.txt
      - run: sudo pip install -r requirements-dev.txt
      - run: nosetests

orbs:
  aws-s3: circleci/aws-s3@2.0.0

workflows:
  version: 2

  main:
    jobs:
      - pre_commit_deps
      - pre_commit_test:
          requires:
            - pre_commit_deps
      - test
      - build:
          requires:
            - pre_commit_test
            - test
      - publish:
          requires:
            - build
          context:
            - org-global
